baseURL = 'https://filipecarneiro.github.io/hugo-bootstrap-theme/'
title = "Hugo Bootstrap Theme"
author = "Filipe Carneiro"
copyright = "Open-source <a class=\"text-muted text-decoration-none\" href=\"https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE\">MIT</a> Licensed."

languageCode = "en" # For the internal RSS template (and for the html lang attribute)
DefaultContentLanguage = "en"
timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
